name: anpr
description: A Dart application using TSANPR
version: 1.0.0

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  image: ^4.1.3
  ffi: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
