name = "ts_anpr"
version = "3.1.3"
description = "Ada example for TS-ANPR engine - Automatic Number Plate Recognition"
authors = ["TS-Solution Corp."]
maintainers = ["bobhyun@gmail.com"]
maintainers-logins = ["bobhyun"]
licenses = "MIT"
website = "https://github.com/bobhyun/TS-ANPR"
tags = ["anpr", "ocr", "computer-vision", "license-plate"]

executables = ["anpr"]
project-files = ["anpr.gpr"]

[build-switches]
"*".style_checks = "No"
