/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_anpr_TSANPR */

#ifndef _Included_com_example_anpr_TSANPR
#define _Included_com_example_anpr_TSANPR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_anpr_TSANPR
 * Method:    anpr_initialize
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anpr_TSANPR_anpr_1initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_anpr_TSANPR
 * Method:    anpr_read_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anpr_TSANPR_anpr_1read_1file
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_example_anpr_TSANPR
 * Method:    anpr_read_pixels
 * Signature: ([BJJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_anpr_TSANPR_anpr_1read_1pixels
  (JNIEnv *, jobject, jbyteArray, jlong, jlong, jlong, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
